

# For now just simply print out the commands
message(STATUS "CMAKE_FIND_PACKAGE_NAME: ${CMAKE_FIND_PACKAGE_NAME}")
message(STATUS "FIND_REQUIRED: ${${CMAKE_FIND_PACKAGE_NAME}_FIND_REQUIRED}")
message(STATUS "FIND_VERSION: ${${CMAKE_FIND_PACKAGE_NAME}_FIND_VERSION}")
message(STATUS "FIND_COMPONENTS: ${${CMAKE_FIND_PACKAGE_NAME}_FIND_COMPONENTS}")